//
// Created by 13967 on 2021/12/17.
//

#ifndef MY_APPLICATION_ACCESSJAVACONSTRUCTIONMETHOD_H
#define MY_APPLICATION_ACCESSJAVACONSTRUCTIONMETHOD_H


class Accessjavaconstructionmethod {

};


#endif //MY_APPLICATION_ACCESSJAVACONSTRUCTIONMETHOD_H
